const seedTags = [
  { name: 'a11y' },
  { name: 'Agile' },
  { name: 'Agile methodology' },
  { name: 'AJAX' },
  { name: 'algorithms' },
  { name: 'Android' },
  { name: 'Angular' },
  { name: 'Angular 2' },
  { name: 'Angular 4' },
  { name: 'AngularJS' },
  { name: 'APIs' },
  { name: 'architecture' },
  { name: 'AWS' },
  { name: 'AWS Lambda' },
  { name: 'back-end' },
  { name: 'Bayesian analysis' },
  { name: 'BDD' },
  { name: 'biography' },
  { name: 'Bootstrap' },
  { name: 'C#' },
  { name: 'CanJS' },
  { name: 'Canvas' },
  { name: 'Chrome' },
  { name: 'CLI' },
  { name: 'Clojure' },
  { name: 'closure' },
  { name: 'code quality' },
  { name: 'CoffeeScript' },
  { name: 'communication' },
  { name: 'CouchDB' },
  { name: 'CS' },
  { name: 'CSS' },
  { name: 'CSS animations' },
  { name: 'CSS Grid' },
  { name: 'CSS transform' },
  { name: 'CSS transitions' },
  { name: 'D3.js' },
  { name: 'data analysis' },
  { name: 'data science' },
  { name: 'data structures' },
  { name: 'data visualization' },
  { name: 'database' },
  { name: 'debugging' },
  { name: 'deploying' },
  { name: 'design patterns' },
  { name: 'DevOps' },
  { name: 'Digital Ocean' },
  { name: 'Docker' },
  { name: 'Elixir' },
  { name: 'Elm' },
  { name: 'Ember' },
  { name: 'Erlang' },
  { name: 'ES2015' },
  { name: 'ES6' },
  { name: 'exercises' },
  { name: 'Express' },
  { name: 'Factor' },
  { name: 'Fetch API' },
  { name: 'Firebase' },
  { name: 'Flexbox' },
  { name: 'front-end' },
  { name: 'full-stack' },
  { name: 'functional programming' },
  { name: 'git' },
  { name: 'GitHub' },
  { name: 'Golang' },
  { name: 'GraphQL' },
  { name: 'GUI' },
  { name: 'hardware' },
  { name: 'Haskell' },
  { name: 'HBase' },
  { name: 'history' },
  { name: 'HTML' },
  { name: 'Idris' },
  { name: 'Immutant' },
  { name: 'InDesign' },
  { name: 'interview prep' },
  { name: 'interviewing' },
  { name: 'Io' },
  { name: 'iOS' },
  { name: 'IoT' },
  { name: 'Java' },
  { name: 'JavaScript' },
  { name: 'Jekyll' },
  { name: 'job hunting' },
  { name: 'jQuery' },
  { name: 'Julia' },
  { name: 'leadership' },
  { name: 'lean' },
  { name: 'Linux' },
  { name: 'Lua' },
  { name: 'machine learning' },
  { name: 'map/reduce' },
  { name: 'Markdown' },
  { name: 'math' },
  { name: 'Matplotlib' },
  { name: 'MEAN stack' },
  { name: 'Meteor' },
  { name: 'MiniKanren' },
  { name: 'mobile web' },
  { name: 'MongoDB' },
  { name: 'MySQL' },
  { name: 'Natural Language Processing' },
  { name: 'Neo4J' },
  { name: 'networking' },
  { name: 'Node' },
  { name: 'OOP' },
  { name: 'Page Layout' },
  { name: 'penetration testing' },
  { name: 'performance' },
  { name: 'PHP' },
  { name: 'PMP' },
  { name: 'PostgreSQL' },
  { name: 'practice' },
  { name: 'product design' },
  { name: 'product management' },
  { name: 'productivity' },
  { name: 'professional development' },
  { name: 'progressive enhancement' },
  { name: 'progressive web apps' },
  { name: 'project management' },
  { name: 'Prolog' },
  { name: 'public speaking' },
  { name: 'PureCSS' },
  { name: 'Python' },
  { name: 'R' },
  { name: 'Rails' },
  { name: 'Raspberry Pi' },
  { name: 'React' },
  { name: 'React Native' },
  { name: 'React Router' },
  { name: 'reactive programming' },
  { name: 'Redis' },
  { name: 'Redux' },
  { name: 'RegEx' },
  { name: 'responsive design' },
  { name: 'REST' },
  { name: 'Riak' },
  { name: 'Ring' },
  { name: 'Ruby' },
  { name: 'Ruby on Rails' },
  { name: 'RubyMotion' },
  { name: 'Sass' },
  { name: 'Scala' },
  { name: 'scope' },
  { name: 'Scrum' },
  { name: 'security' },
  { name: 'serverless' },
  { name: 'Sinatra' },
  { name: 'soft skills' },
  { name: 'Spark' },
  { name: 'SQL' },
  { name: 'SQLite3' },
  { name: 'static sites' },
  { name: 'study skills' },
  { name: 'SVG' },
  { name: 'Swift' },
  { name: 'TDD' },
  { name: 'testing' },
  { name: 'TypeScript' },
  { name: 'UX' },
  { name: 'version control' },
  { name: 'Vim' },
  { name: 'Vue Router' },
  { name: 'VueJS' },
  { name: 'Vuex' },
  { name: 'waterfall' },
  { name: 'Webmachine' },
  { name: 'Webpack' },
  { name: 'whiteboarding' },
  { name: 'Windows' },
  { name: 'women in tech' },
  { name: 'writing' },
  { name: 'Xamarin' },
  { name: 'Yesod' },
];

module.exports = seedTags;
